// Generated by CoffeeScript 1.9.3
(function() {
  func(5, {
    event: function() {
      return 45;
    },
    val: 10
  });

  func(5, {
    event: function(e) {
      if (e.something) {
        return 36;
      } else {
        return 45;
      }
    },
    val: 10
  });

  func1(1, func2(2, 3));

}).call(this);
